get rid of "implicit declaration of function is...()" warnings
The functions isspace(), isupper(), is[x]digit() were declared implicitely
(i.e. the header file was missing), leading to compiler warnings such as the
following:

---
gcc -g -o mktables mktables.c
mktables.c: In function ‘printCall’:
mktables.c:215:9: warning: implicit declaration of function ‘isspace’ [-Wimplicit-function-declaration]
  while (isspace(*p) && (*p))
         ^
---

By including the correct header "ctype.h", the warnings are gone.